### ISSUE TITLE
Shift+Click transaction selection including scheduled transaction throws fatal error

### ISSUE THREAD

**Issue by btrautmann** [actualbudget/releases#54]
**Platform:** Web
**To reproduce:** Click a scheduled transaction, then hit Shift + Click on non-scheduled transaction, and a fatal error is thrown.

```
TypeError: Cannot read properties of undefined (reading 'id') at https://app.actualbudget.com/static/js/main.d0c119f5.chunk.js:1:59939 at m (https://app.actualbudget.com/static/js/main.d0c119f5.chunk.js:1:59474) at Object.selectedItems (https://app.actualbudget.com/static/js/main.d0c119f5.chunk.js:1:59921) at Object.ea [as useReducer] (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:565011) at t.useReducer (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:505136) at y (https://app.actualbudget.com/static/js/main.d0c119f5.chunk.js:1:59525) at E (https://app.actualbudget.com/static/js/main.d0c119f5.chunk.js:1:61919) at Xi (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:563416) at Fa (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:572304) at bu (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:611165) at bs (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:602570) at ys (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:602495) at ls (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:599497) at https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:550687 at t.unstable_runWithPriority (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:626355) at qo (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:550397) at Go (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:550633) at $o (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:550568) at N (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:620115) at https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:527891 at HTMLDocument.i (https://app.actualbudget.com/static/js/3.52ea9243.chunk.js:1:51970)
```
☝️ Likely not helpful since it's obfuscated, but it's very easy to reproduce.

Doing the same in only non-scheduled transactions works as expected.

**Comment by jlongster** [comment]
Sorry about the noise! Still polishing my integration :)
